a.out: main.cpp Board.hpp.gch AI.hpp.gch RandomAI.hpp.gch User.hpp.gch
    -std=c++11 main.cpp
Board.hpp.gch: Board.hpp
    -std=c++11 Board.hpp
AI.hpp.gch: AI.hpp
    -std=c++11 AI.hpp
RandomAI.hpp.gch: RandomAI.hpp
    -std=c++11 RandomAI.hpp
User.hpp.gch: User.hpp
    -std=c++11 User.hpp
